name: Lighthouse Tests with Email

on:
  # schedule:
    # - cron: '0 8 * * 1-5' # Щодня о 8:00 ранку (UTC)
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    env:
      WEB_URL: https://devurai.com 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm install
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      
      - name: Run Lighthouse tests
        run: xvfb-run npm run test:lighthouse
      
      - name: Upload blob report to GitHub Actions Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: all-blob-reports
          path: blob-report
          retention-days: 1
      - name: Send Lighthouse report via email
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Lighthouse Report for devurai.com"
          to: ms@devurai.com
          from: "Lighthouse Bot <shared@devurai.com>"
          body: "Дивись HTML-звіт у вкладенні."
          attachments: reports/html-report/index.html 
